name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Lint
      run: cargo clippy --tests --benches --verbose -- --no-deps -D warnings -W clippy::pedantic -W clippy::all -W clippy::undocumented_unsafe_blocks
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  test_miri:
      name: Test (Miri)
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3
        - uses: actions-rs/toolchain@v1
          with:
            profile: minimal
            toolchain: nightly
            override: true
            components: miri
        - uses: actions-rs/cargo@v1
          with:
            command: miri
            args: test